import { Product, Collection, Banner, StoreSettings, FAQItem, ReviewItem } from "../types";

export const seedCollections: Collection[] = [
  {
    id: "god-cases",
    name: "God Cases",
    slug: "god-cases",
    image: "god-ganesh",
    description: "Spiritual, sacred, and serene cover prints radiating divine vibes.",
    isVisible: true,
  },
  {
    id: "tvk-cases",
    name: "TVK Cases",
    slug: "tvk-cases",
    image: "tvk-vijay",
    description: "Official TVK Vijay party thematic stylish glossy cases.",
    isVisible: true,
  },
  {
    id: "girly-cases",
    name: "Girly Cases",
    slug: "girly-cases",
    image: "girly-love",
    description: "Charming, cute pink, love-struck glossy designer models.",
    isVisible: true,
  },
  {
    id: "trendy-cases",
    name: "Trendy Cases",
    slug: "trendy-cases",
    image: "mandala-eye",
    description: "Hottest, viral, and psychedelic graphic phone casings.",
    isVisible: true,
  },
  {
    id: "photo-cases",
    name: "Photo Cases",
    slug: "photo-cases",
    image: "default",
    description: "Turn your favourite photo into a premium glossy phone case — your memory, your style.",
    isVisible: true,
  },
  {
    id: "photo-name-cases",
    name: "Photo + Name Cases",
    slug: "photo-name-cases",
    image: "default",
    description: "Personalise your case with your photo AND a custom printed name — perfect for gifting.",
    isVisible: true,
  },
];

// Seed exactly 10 premium sample products for each of the 4 collections
export const seedProducts: Omit<Product, "createdAt" | "updatedAt">[] = [
  // --- 1. GOD CASES (10 Items) ---
  {
    id: "god-ganesh-glossy",
    title: "Divine Ganesha Gold Frame Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Serene gold-accented portrait of Ganesha on a high-gloss structural hardback with triple-lens guard protection.",
    collectionId: "god-cases",
    tags: ["god", "devotional", "ganesha", "bestseller"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    images: ["god-ganesh"],
    models: ["iPhone 15 Pro", "iPhone 15 Pro Max", "Samsung S24 Ultra", "OnePlus 12"],
    collectionIds: [],
  },
  {
    id: "god-shiva-cosmic",
    title: "Cosmic Shiva Trishul Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Mystical midnight blue theme featuring Lord Shiva's Trishul and Damru with deep space starry vectors.",
    collectionId: "god-cases",
    tags: ["god", "shiva", "cosmic", "spiritual"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: false,
    images: ["islamic-sabr"], // generic procedural visual pattern
    models: ["iPhone 15 Pro", "Samsung S24 Ultra"],
    collectionIds: [],
  },
  {
    id: "god-krishna-murli",
    title: "Divine Krishna Flute Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Vibrant yellow backcover representing Lord Krishna's divine feather and golden flute surrounded by sacred peacock colors.",
    collectionId: "god-cases",
    tags: ["god", "krishna", "peacock", "devotional"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: false,
    images: ["god-ganesh"],
    models: ["iPhone 15 Pro Max", "OnePlus 12R", "Redmi Note 13 Pro"],
    collectionIds: [],
  },
  {
    id: "god-hanuman-bajrang",
    title: "Sankat Mochan Hanuman Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Powerful portrait of Bajrangbali Hanuman with golden aura reflections on reinforced glossy acrylic.",
    collectionId: "god-cases",
    tags: ["god", "hanuman", "aurashield", "spiritual"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: true,
    images: ["god-ganesh"],
    models: ["iPhone 14 Pro Max", "Samsung S24", "Poco X6 Pro"],
    collectionIds: [],
  },
  {
    id: "god-durga-shakti",
    title: "Maa Durga Shakti Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Intense red and gold aesthetic of Adi Shakti Durga representing protection, power, and high-fidelity gloss sheen.",
    collectionId: "god-cases",
    tags: ["god", "durga", "shakti", "heritage"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    images: ["god-ganesh"],
    models: ["iPhone 15 Pro", "OnePlus Nord 4"],
    collectionIds: [],
  },
  {
    id: "god-murugan-vel",
    title: "Lord Murugan Vel Metal Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "High-fidelity divine representation of Lord Murugan's Vel on an armored scratch-resistant glossy casing.",
    collectionId: "god-cases",
    tags: ["god", "murugan", "religion", "vel", "best-seller"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: true,
    images: ["god-ganesh"],
    models: ["iPhone 15 Pro", "iPhone 14 Pro", "Samsung S24 Ultra", "OnePlus 12"],
    collectionIds: [],
  },
  {
    id: "god-ayyappa-swamy",
    title: "Sabarimala Swamy Ayyappa Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Serene sacred design representing Swamy Sharanam Ayyappa in classic black velvet and gold border printing.",
    collectionId: "god-cases",
    tags: ["god", "ayyappa", "sabarimala", "classic"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: false,
    images: ["god-ganesh"],
    models: ["iPhone 15 Pro Max", "Samsung A55"],
    collectionIds: [],
  },
  {
    id: "god-jesus-cross",
    title: "Sacred Heart Jesus Cross Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Clean religious layout featuring the elegant crucifix outline on a midnight velvet dark composite backing.",
    collectionId: "god-cases",
    tags: ["god", "jesus", "christ", "church"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    images: ["islamic-sabr"],
    models: ["iPhone 15", "iPhone 13 Pro"],
    collectionIds: [],
  },
  {
    id: "god-mecca-madina",
    title: "Blessed Mecca Madina Gold Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Gorgeous golden floral outlines centering the holy Kaaba sanctuary print on hard gloss high-impact shielding.",
    collectionId: "god-cases",
    tags: ["god", "mecca", "islamic", "blessed"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: true,
    images: ["islamic-sabr"],
    models: ["iPhone 15 Pro", "Samsung S24 Ultra", "OnePlus 12R", "Oppo Reno 11"],
    collectionIds: [],
  },
  {
    id: "god-buddha-serene",
    title: "Serene Buddha Lotus Garden Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Tranquil zen-inspired pastel green background representing peaceful Lord Buddha in deep sitting meditation.",
    collectionId: "god-cases",
    tags: ["god", "buddha", "zen", "serene", "meditation"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    images: ["god-ganesh"],
    models: ["iPhone 15 Pro Max", "Vivo V30 Pro"],
    collectionIds: [],
  },

  // --- 2. TVK CASES (10 Items) ---
  {
    id: "tvk-thalapathy-royal",
    title: "TVK Thalapathy Vijay Royal Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "High-definition photo design of Thalapathy Vijay with the official lion emblems and gold borders.",
    collectionId: "tvk-cases",
    tags: ["tvk", "vijay", "thalapathy", "royal"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: true,
    images: ["tvk-vijay"],
    models: ["iPhone 15 Pro Max", "iPhone 15 Pro", "Samsung S24 Ultra", "OnePlus 12"],
    collectionIds: [],
  },
  {
    id: "tvk-lion-emblem",
    title: "TVK Lion Heart Golden Emblem Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Elegant layout focusing on the roaring lion motif of the Tamizhaga Vettri Kazhagam flag on velvet red background.",
    collectionId: "tvk-cases",
    tags: ["tvk", "lion", "gold", "official"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: false,
    images: ["tvk-vijay"],
    models: ["iPhone 15 Pro", "Samsung S23 Ultra"],
    collectionIds: [],
  },
  {
    id: "tvk-victory-flag",
    title: "TVK Red-Yellow Victory Flag Metal Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Draped party flag layout featuring striking division of red and yellow with golden sparkles.",
    collectionId: "tvk-cases",
    tags: ["tvk", "flag", "theme", "loyalty"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    images: ["tvk-vijay"],
    models: ["iPhone 15 Pro Max", "OnePlus Nord CE 4"],
    collectionIds: [],
  },
  {
    id: "tvk-vijay-smile",
    title: "Thalapathy Vijay Signature Smile Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Unmatched photorealistic premium print capturing the warm welcoming smile of TVK's leadership.",
    collectionId: "tvk-cases",
    tags: ["tvk", "vijay", "smile", "leader"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    images: ["tvk-vijay"],
    models: ["iPhone 15 Pro", "Samsung S24", "Vivo T3"],
    collectionIds: [],
  },
  {
    id: "tvk-party-pride",
    title: "TVK Party Cadre Pride Banner Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Specially printed case with high-contract party symbols for passionate cadres and flag bearers.",
    collectionId: "tvk-cases",
    tags: ["tvk", "pride", "cadre", "symbol"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: false,
    images: ["tvk-vijay"],
    models: ["iPhone 14 Pro", "Realme 12"],
    collectionIds: [],
  },
  {
    id: "tvk-commander-gold",
    title: "TVK Commander Golden Starlight Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Vibrant yellow gradient layout with Thalapathy Vijay silhouette standing in victory posture.",
    collectionId: "tvk-cases",
    tags: ["tvk", "commander", "gold", "starlight"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    images: ["tvk-vijay"],
    models: ["iPhone 15 Pro Max", "Samsung S24 Ultra", "Oppo Reno 11 Pro"],
    collectionIds: [],
  },
  {
    id: "tvk-vijay-mass",
    title: "TVK Vijay Mass Action Silhouette Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Stylized stencil line art of Vijay wearing custom party sash on tough glossy rubber bumper chassis.",
    collectionId: "tvk-cases",
    tags: ["tvk", "mass", "art", "cool"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: false,
    images: ["tvk-vijay"],
    models: ["iPhone 15 Pro", "Poco F6 Pro"],
    collectionIds: [],
  },
  {
    id: "tvk-democracy-torch",
    title: "TVK Democratic Leader Velvet Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Deep matte black with gold outlines portraying Vijay at the historic TVK conference.",
    collectionId: "tvk-cases",
    tags: ["tvk", "leader", "conference", "limited"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    images: ["tvk-vijay"],
    models: ["iPhone 15 Plus", "OnePlus 12"],
    collectionIds: [],
  },
  {
    id: "tvk-flagship-limited",
    title: "TVK Flagship Limited Edition Matte Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Official collective launch edition casing with double layered glossy coat and shock-absorption ring.",
    collectionId: "tvk-cases",
    tags: ["tvk", "flagship", "limited", "exclusive"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: false,
    images: ["tvk-vijay"],
    models: ["iPhone 15 Pro Max", "Samsung S24 Ultra"],
    collectionIds: [],
  },
  {
    id: "tvk-vijay-retro",
    title: "Vintage Thalapathy Retro Cinematic Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Nostalgic 90s vintage filmstrip collage of the superstar Thalapathy Vijay with official TVK watermarks.",
    collectionId: "tvk-cases",
    tags: ["tvk", "retro", "cinema", "vintage"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    images: ["tvk-vijay"],
    models: ["iPhone 15 Pro", "OnePlus 12R", "Redmi Note 13"],
    collectionIds: [],
  },

  // --- 3. GIRLY CASES (10 Items) ---
  {
    id: "girly-pink-kawaii",
    title: "Cute Kawaii Pink Bear Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Aesthetic soft pink teddy layout with adorable smiling bubble characters. Perfect gloss glaze surface.",
    collectionId: "girly-cases",
    tags: ["girly", "pink", "kawaii", "cute"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: true,
    images: ["girly-love"],
    models: ["iPhone 13", "iPhone 14 Pro", "iPhone 15 Pro Max", "Samsung S24"],
    collectionIds: [],
  },
  {
    id: "girly-butterfly-dream",
    title: "Dreamy Pastel Butterfly Glass Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Beautiful floating holographic butterflies reflecting spectrum colors under natural ambient daylight.",
    collectionId: "girly-cases",
    tags: ["girly", "butterfly", "pastel", "holo"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: false,
    images: ["girly-love"],
    models: ["iPhone 15 Pro Max", "Vivo V30 Pro", "Oppo F25 Pro"],
    collectionIds: [],
  },
  {
    id: "girly-cherry-blossom",
    title: "Japanese Sakura Cherry Blossom Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Elegant paint stroke cherry blossom branches with gentle petals drifting down a white translucent backdrop.",
    collectionId: "girly-cases",
    tags: ["girly", "flower", "sakura", "blooms"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: false,
    images: ["girly-love"],
    models: ["iPhone 15 Pro", "Samsung S24 Ultra", "OnePlus Nord CE 4"],
    collectionIds: [],
  },
  {
    id: "girly-glitter-star",
    title: "Stardust Pink Sparkle Metal Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Vibrant hot pink starfield with fine-grade cosmetic sparkles layered beneath thick crystal resin.",
    collectionId: "girly-cases",
    tags: ["girly", "sparkle", "star", "hotpink"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: true,
    images: ["girly-love"],
    models: ["iPhone 14 Pro Max", "Samsung S23", "Realme 12 Pro+"],
    collectionIds: [],
  },
  {
    id: "girly-me-heart",
    title: "Sweetheart Love Letters Shell Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Charming red hearts grid patterned neatly over premium blush pink glossy casing.",
    collectionId: "girly-cases",
    tags: ["girly", "hearts", "love", "classic"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: false,
    images: ["girly-love"],
    models: ["iPhone 15", "Oppo Reno 11 Pro"],
    collectionIds: [],
  },
  {
    id: "girly-daisy-meadow",
    title: "Spring Daisy Meadow Clear Casing",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Sunny bright miniature daisy blossoms scattered evenly with high quality UV light resistance to prevent yellowing.",
    collectionId: "girly-cases",
    tags: ["girly", "daisy", "clear", "nature"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    images: ["girly-love"],
    models: ["iPhone 15 Pro Max", "OnePlus 12"],
    collectionIds: [],
  },
  {
    id: "girly-lavender-haze",
    title: "Pastel Lavender Gold Flake Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Elegant cloudy violet layout decorated with actual mimicking gold foil flakes for a high-end royal look.",
    collectionId: "girly-cases",
    tags: ["girly", "lavender", "goldflake", "luxury"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: true,
    images: ["girly-love"],
    models: ["iPhone 15 Plus", "Samsung S24+"],
    collectionIds: [],
  },
  {
    id: "girly-cat-whiskers",
    title: "Cute Peach Neko Cat Ears Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Lovable sleeping cat whiskers cartoon illustration over warm peachy peach background tint.",
    collectionId: "girly-cases",
    tags: ["girly", "cat", "neko", "pet"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    images: ["girly-love"],
    models: ["iPhone 15 Pro", "Realme 12"],
    collectionIds: [],
  },
  {
    id: "girly-unicorn-magic",
    title: "Magic Purple Unicorn Spark Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Fantasy pastel purple unicorn profile amidst shooting stars and rainbow constellations.",
    collectionId: "girly-cases",
    tags: ["girly", "unicorn", "purple", "fantasy"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    images: ["girly-love"],
    models: ["iPhone 13 Pro Max", "Vivo T3"],
    collectionIds: [],
  },
  {
    id: "girly-rose-gold",
    title: "Vintage Dried Rose Gold Foil Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Chic vintage aesthetic representing dried crimson rose petals layered with gold outlines.",
    collectionId: "girly-cases",
    tags: ["girly", "rose", "vintage", "romantic"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    images: ["girly-love"],
    models: ["iPhone 15 Pro Max", "Redmi Note 13 Pro+"],
    collectionIds: [],
  },

  // --- 4. TRENDY CASES (10 Items) ---
  {
    id: "trendy-neon-cyber",
    title: "Cyberpunk Tokyo Neon Street Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Atmospheric neon glowing elements depicting Tokyo kanji lettering and grid lines for a technical synthwave feel.",
    collectionId: "trendy-cases",
    tags: ["trendy", "neon", "cyberpunk", "tokyo"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    images: ["mandala-eye"],
    models: ["iPhone 15 Pro Max", "Samsung S24 Ultra", "OnePlus 12", "Poco X6 Pro"],
    collectionIds: [],
  },
  {
    id: "trendy-liquid-marble",
    title: "Liquid Gold Galactic Marble Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Luxurious fluid swirled colors of deep obsidian, teal, and liquid gold veins on high impact acrylic casing.",
    collectionId: "trendy-cases",
    tags: ["trendy", "marble", "fluid", "goldvein"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    images: ["mandala-eye"],
    models: ["iPhone 15 Pro", "Samsung S24 Ultra", "Realme GT 6"],
    collectionIds: [],
  },
  {
    id: "trendy-mandala-trippy",
    title: "Mystic Neon Mandala Trippy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Psychedelic optical matrix designs centered around a vivid spiritual neon outer lens.",
    collectionId: "trendy-cases",
    tags: ["trendy", "trippy", "neon", "mandala", "psychedelic"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    images: ["mandala-eye"],
    models: ["iPhone 15 Pro Max", "Samsung S24 Ultra", "Vivo V30 Pro", "Poco X6 Pro"],
    collectionIds: [],
  },
  {
    id: "trendy-vaporwave-retro",
    title: "Vaporwave Sunset Grid Nostalgia Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Sleek 80s wireframe grids with pixel-perfect glowing magenta sun outline on high fidelity cover plate.",
    collectionId: "trendy-cases",
    tags: ["trendy", "retro", "vaporwave", "synthwave"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: false,
    images: ["mandala-eye"],
    models: ["iPhone 15", "OnePlus Nord 4"],
    collectionIds: [],
  },
  {
    id: "trendy-retro-abstract",
    title: "Retro 90s Memphis Pattern Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Playful squizzles, zig-zags, and pastel shapes on a stark white layout for direct vintage vibes.",
    collectionId: "trendy-cases",
    tags: ["trendy", "retro", "90s", "memphis"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    images: ["mandala-eye"],
    models: ["iPhone 14 Pro", "Samsung A55"],
    collectionIds: [],
  },
  {
    id: "trendy-stealth-carbon",
    title: "Stealth Matte Carbon Fiber Armor Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Textured military look carbon weave pattern with side tactile grip and raised shock borders.",
    collectionId: "trendy-cases",
    tags: ["trendy", "carbon", "stealth", "armor"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    images: ["minimal-slate"],
    models: ["iPhone 15 Pro Max", "Samsung S24 Ultra", "OnePlus 12"],
    collectionIds: [],
  },
  {
    id: "trendy-geometric-gold",
    title: "Geometric Gold Hexagon Matrix Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Sleek black geometric structure lined with shiny golden lines forming continuous interlocking honeycombs.",
    collectionId: "trendy-cases",
    tags: ["trendy", "geometric", "goldline", "honeycomb"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    images: ["mandala-eye"],
    models: ["iPhone 15 Pro", "OnePlus 12R"],
    collectionIds: [],
  },
  {
    id: "trendy-cosmic-astronaut",
    title: "Cosmic Lost Astronaut Nebula Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Cute floating astronaut sitting over a glowing pink cloud system with distant planet graphics.",
    collectionId: "trendy-cases",
    tags: ["trendy", "cosmic", "space", "astronaut"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: false,
    images: ["mandala-eye"],
    models: ["iPhone 15 Pro Max", "Vivo V30"],
    collectionIds: [],
  },
  {
    id: "trendy-ocean-wave",
    title: "Kanagawa Great Wave Glossy Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Custom digital render of the legendary Great Wave with golden spray details on flawless glossy backing.",
    collectionId: "trendy-cases",
    tags: ["trendy", "wave", "kanagawa", "classic"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: false,
    images: ["mandala-eye"],
    models: ["iPhone 15", "Oppo F25 Pro"],
    collectionIds: [],
  },
  {
    id: "trendy-acid-graffiti",
    title: "Acid Punk Street Graffiti Splatter Case",
    price: 299,
    comparePrice: 1200,
    discount: 75,
    description: "Vandal style graffiti dripping typography and neon paint splatter outlines. Ultimate street fashion statement.",
    collectionId: "trendy-cases",
    tags: ["trendy", "punk", "graffiti", "streetwear"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: true,
    images: ["mandala-eye"],
    models: ["iPhone 15 Pro Max", "Samsung S24 Ultra", "OnePlus 12"],
    collectionIds: [],
  },

  // ── Photo Cases ────────────────────────────────────────────────────────────
  {
    id: "photo-case-classic",
    title: "Custom Photo Case",
    price: 349,
    comparePrice: 699,
    discount: 50,
    description: "Upload any photo — your pet, your couple selfie, your squad — and we'll print it in vivid glossy quality on a premium shockproof hard case. Every case is unique, just like you.",
    collectionId: "photo-cases",
    tags: ["photo", "custom", "personalised", "gift"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    images: ["default"],
    models: ["iPhone 15 Pro Max", "Samsung S24 Ultra", "OnePlus 12"],
    collectionIds: [],
  },
  {
    id: "photo-case-premium",
    title: "Premium Photo Case — Matte Finish",
    price: 399,
    comparePrice: 799,
    discount: 50,
    description: "High-res photo print with a soft matte anti-glare coating. Fingerprint-resistant, super grippy, and vivid colours that don't fade. Perfect personalised gift.",
    collectionId: "photo-cases",
    tags: ["photo", "matte", "gift", "personalised"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: true,
    images: ["default"],
    models: ["iPhone 15 Pro Max", "Samsung S24 Ultra", "OnePlus 12"],
    collectionIds: [],
  },

  // ── Photo + Name Cases ─────────────────────────────────────────────────────
  {
    id: "photo-name-case-classic",
    title: "Photo + Name Case",
    price: 449,
    comparePrice: 899,
    discount: 50,
    description: "Upload your favourite photo AND add a custom name in gold/white cursive lettering. The ultimate personalised case — great for birthdays, anniversaries & gifting.",
    collectionId: "photo-name-cases",
    tags: ["photo", "name", "custom", "personalised", "gift"],
    stockStatus: "in_stock",
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: true,
    images: ["default"],
    models: ["iPhone 15 Pro Max", "Samsung S24 Ultra", "OnePlus 12"],
    collectionIds: [],
  },
  {
    id: "photo-name-case-premium",
    title: "Premium Photo + Name Case — Glossy",
    price: 499,
    comparePrice: 999,
    discount: 50,
    description: "Crystal-clear photo print with vibrant gold name lettering on a high-gloss hard casing. Looks jaw-dropping and lasts years without yellowing or fading.",
    collectionId: "photo-name-cases",
    tags: ["photo", "name", "glossy", "premium", "gift"],
    stockStatus: "in_stock",
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    images: ["default"],
    models: ["iPhone 15 Pro Max", "Samsung S24 Ultra", "OnePlus 12"],
    collectionIds: [],
  },
];

// Seed Banners
export const seedBanners: Banner[] = [
  {
    id: "banner-1",
    title: "Mobile Covers That Suit Your Style!",
    subtitle: "Premium Acrylic Glossy Covers with Triple-Lens Shock Armor",
    imageUrl: "https://images.unsplash.com/photo-1601784551146-12c4eef89174?auto=format&fit=crop&w=1200&q=80",
    link: "/collections/trendy-cases",
    active: true,
    order: 1,
  },
  {
    id: "banner-2",
    title: "Buy 2 Get 100 Rs. Instant Discount",
    subtitle: "Premium Devotional Gloss Cover & God Cases collections",
    imageUrl: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=1200&q=80",
    link: "/collections/god-cases",
    active: true,
    order: 2,
  },
];

// Default dynamic phone brands & models configuration
export const defaultBrandModels: Record<string, string[]> = {
  "iPhone Cases": ["iPhone 15 Pro Max", "iPhone 15 Pro", "iPhone 15", "iPhone 14 Pro Max", "iPhone 14 Pro", "iPhone 13 Pro Max", "iPhone 13 Pro", "iPhone 13"],
  "Samsung Cases": ["Samsung S24 Ultra", "Samsung S24+", "Samsung S24", "Samsung S23 Ultra", "Samsung S23", "Samsung A55", "Samsung A35"],
  "OnePlus Cases": ["OnePlus 12", "OnePlus 12R", "OnePlus 11", "OnePlus Nord 4", "OnePlus Nord CE 4"],
  "Vivo Cases": ["Vivo V30 Pro", "Vivo V30", "Vivo Y200", "Vivo T3"],
  "Oppo Cases": ["Oppo Reno 11 Pro", "Oppo Reno 11", "Oppo F25 Pro"],
  "Realme Cases": ["Realme GT 6", "Realme 12 Pro+", "Realme 12", "Realme Narzo 75"],
  "Redmi Cases": ["Redmi Note 13 Pro+", "Redmi Note 13 Pro", "Redmi Note 13", "Redmi 13C"],
  "Poco Cases": ["Poco F6 Pro", "Poco X6 Pro", "Poco M6 Pro"]
};

// Seed Settings with brandModels
export const seedSettings: StoreSettings = {
  announcements: [
    { id: "a-1", text: "Buy 2 Get 100₹ Instant Discount Code: SAVE100" },
    { id: "a-2", text: "Free Premium Shipping & Secure Transit All Over India" },
    { id: "a-3", text: "New TVK & God cases collections dropped! Get 75% OFF!" },
  ],
  freeShippingThreshold: 499,
  contactEmail: "support@fabcoverz.com",
  contactPhone: "+91 98765 43210",
  contactAddress: "Chennai, Tamil Nadu, India",
  instagramUrl: "https://instagram.com/fabcoverz",
  facebookUrl: "https://facebook.com/fabcoverz",
  reassuranceCard1Title: "10-Ft Drop Protection Armor",
  reassuranceCard1Body: "Metal Glossy Case built with deep soft shock-absorbing TPU frame nodes & polished scratch-resistant glossy print face.",
  reassuranceCard2Title: "Custom Printed Cursives",
  reassuranceCard2Body: "Type your signature cursive Gold/White fonts directly inside our custom models. Personalized exactly according to order.",
  reassuranceCard3Title: "Free Defect Replacements",
  reassuranceCard3Body: "Any transit harm, print blemishes or blemish cracks are covered by our 7-day 100% Free Replacements Guarantee.",
  offerText: "Limited Period Festive Offer",
  brandModels: defaultBrandModels,
  aboutSectionTitle: "Premium Durability Meets Modern Aesthetics",
  aboutSectionSubtitle: "At FabCoverz, we believe your phone is an extension of your individual personality. We combine high-grade materials with advanced sublimation printing techniques to create our signature Metal Glossy Cases.",
  aboutSectionDesc1: "Based proudly in Chennai, India, our team has built a community around custom lettering, spiritual/faith-focused graphics, and bold pop-culture cases. Each cover we produce features full-frame shock absorbing defense rims paired with our fade-proof glossy plate backings.",
  aboutSectionDesc2: "Standard order processing takes 24 hours and delivery takes 2 to 5 business days across India depending on your location, shipped via express premium logistics.",
  bannerStoryBadge: "OUR BRAND STORY",
  reviewsBadge: "COMMUNITY LOVE",
  reviewsTitle: "Verified Customer Reviews",
  reviewsSubtitle: "See what our 45,000+ happy cover collectors are saying about us.",
  footerDisclaimer: "India's leading e-commerce hub for premium Metal Glossy Cases and premium lettering cover sleeves. Crafting distinct visual shield systems since 2026.",
};

export const seedFAQs: FAQItem[] = [
  {
    id: "faq-1",
    question: "Are these covers hard or soft? What material is used?",
    answer: "FabCoverz utilizes premium 'Metal Glossy Cases'. The sides are made of soft impact-absorbent TPU bumper nodes (providing legendary 10ft drop protection) whereas the back print face is a toughened premium scratch-resistant panel with a magnificent glossy metallic finish. This prevents fading and turns your phone case into a stunning glossy showcase."
  },
  {
    id: "faq-2",
    question: "How do I customize my name on Name Cases?",
    answer: "Choose any product inside our 'Name Cases' collection. On that product page, a text field named 'Enter Customized Name/Initial' will appear. Simply type your custom initials or name! The live preview will dynamically update to reflect your name in cursive lettering. We will print it exactly as configured."
  },
  {
    id: "faq-3",
    question: "What is your Shipping Timeline & Delivery Cost?",
    answer: "We support FREE online payment delivery across India! Secure electronic payments are supported with all major Credit/Debit Cards, UPI (GPay, PhonePe, Paytm, BHIM), and NetBanking. Standard order processing takes 24 hours and delivery takes 3 to 5 business days depending on your location."
  },
  {
    id: "faq-4",
    question: "What is your Refund & Exchange policy?",
    answer: "Since customizable name cases and initial covers are uniquely crafted to order, we do not support standard buyer-remorse refunds. However, if your cover arrives damaged or has print defects, we provide a 100% Free Replacements guarantee! Simply photograph the defect and notify our support team within 7 days."
  }
];

export const seedReviews: ReviewItem[] = [
  {
    id: "review-1",
    name: "Pranesh K.",
    location: "Chennai, TN",
    review: "The Metal Glossy Case looks incredible! The custom hand-cursive gold lettering shines beautifully under the sun. Easily the best cover I have ever owned.",
    rating: 5,
    verified: true
  },
  {
    id: "review-2",
    name: "Sneha Nair",
    location: "Kochi, KL",
    review: "Absolutely loving my God Ganesha cover! The details are so premium and there's no yellowing. Highly recommend FabCoverz if you want elite cases.",
    rating: 5,
    verified: true
  },
  {
    id: "review-3",
    name: "Akash Sharma",
    location: "Mumbai, MH",
    review: "Fits my iPhone S24 perfectly. Dropped it twice already on asphalt and no scratches or dents on my screen or the cover. Delivery was also super fast!",
    rating: 5,
    verified: true
  }
];

